using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LegendsLabor.Core.Domain.Entities
{
    public class Base : AuditableEntity
    {
        [Key]
        [Comment("Primary key for the Base entity.")]
        public int Id { get; set; }

        [ForeignKey("Id")]
        [Comment("Foreign key to the Player entity.")]
        public int PlayerId { get; set; }

        [Comment("Navigation property to the Player entity.")]
        public Player Player { get; set; } = null!;

        [Required]
        [MaxLength(100)]
        [Comment("The name of the player's base.")]
        public string Name { get; set; } = string.Empty;

        [Comment("The current level of the base.")]
        public int Level { get; set; }
        [Comment("The capacity of the base (e.g., # of crafting stations, # of guild members housed).")]
        public int Capacity { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        [Comment("The gold income generated by the base per hour.")]
        public decimal IncomePerHour { get; set; }

        [Comment("The date and time when income was last collected from the base.")]
        public DateTime LastCollectedAt { get; set; }
    }
}
